### ISSUE TITLE
`keepOldComments` is not used in the logic

### ISSUE THREAD

**Issue by remal** [tomasbjerre/violation-comments-to-github-lib#11]
Basically, it's a question.

As I can see, `ViolationCommentsToGitHubApi.keepOldComments` field is used only in `withKeepOldComments` and `getKeepOldComments` methods (setter & getter). Does it mean that this library doesn't remove commits that were left from the previous commits/CI run?

My goal is:
1. Run CI for a Pull Request
2. Send all violations to that PR
3. Commit is added / CI job is restarted
4. Remove previous violations sent to this PR
5. Send all violations from the new CI run to that PR

Is this goal achievable?

**Comment by tomasbjerre** [comment]
Yes what you describe should work.

Logic is here:
https://github.com/tomasbjerre/violation-comments-lib/blob/12ecaef0a5c1ae8f81efbf199ec9db96db074b79/src/main/java/se/bjurr/violations/comments/lib/CommentsCreator.java#L171

**Comment by remal** [comment]
Thanks! I'm closing the issue.
